# Generated by Django 6.0.5 on 2026-07-24 09:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

TABLES = (
    "communication_mailbox",
    "communication_email_thread",
    "communication_email_message",
    "communication_email_suppression",
)


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        for table in reversed(TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    initial = True
    atomic = False

    dependencies = [
        ("common", "0027_personalaccesstoken"),
        ("leads", "0013_lead_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("provider_thread_id", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, default="", max_length=512)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("reply_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_threads",
                        to="leads.lead",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_thread",
                "ordering": ("-last_message_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="MailboxConnection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gmail", "Google Gmail")],
                        default="gmail",
                        max_length=16,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("credentials_encrypted", models.TextField()),
                (
                    "provider_history_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_mailbox",
                "ordering": ("email_address",),
            },
        ),
        migrations.CreateModel(
            name="LeadEmailMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("provider_message_id", models.CharField(max_length=255)),
                (
                    "rfc_message_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "in_reply_to",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("references", models.TextField(blank=True, default="")),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=16,
                    ),
                ),
                ("from_address", models.EmailField(max_length=254)),
                ("to_addresses", models.JSONField(blank=True, default=list)),
                ("cc_addresses", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, default="", max_length=512)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                ("provider_labels", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communications.emailthread",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communications.mailboxconnection",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_message",
                "ordering": ("occurred_at", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="emailthread",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="communications.mailboxconnection",
            ),
        ),
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribed", "Unsubscribed"),
                            ("hard_bounce", "Hard bounce"),
                            ("manual", "Manually suppressed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_suppression",
                "indexes": [
                    models.Index(
                        fields=["org", "is_active"],
                        name="communicati_org_id_a55229_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "email_address"),
                        name="uniq_email_suppression_per_org",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mailboxconnection",
            index=models.Index(
                fields=["org", "is_active"], name="communicati_org_id_65fe3e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailboxconnection",
            constraint=models.UniqueConstraint(
                fields=("org", "provider", "email_address"),
                name="uniq_communication_mailbox_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="leademailmessage",
            index=models.Index(
                fields=["org", "thread", "occurred_at"],
                name="communicati_org_id_206809_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leademailmessage",
            index=models.Index(
                fields=["org", "rfc_message_id"], name="communicati_org_id_980c3b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leademailmessage",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "provider_message_id"),
                name="uniq_provider_message_per_mailbox",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["org", "lead", "-last_message_at"],
                name="communicati_org_id_86aa97_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailthread",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "provider_thread_id"),
                name="uniq_provider_thread_per_mailbox",
            ),
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
