# Generated by Django 6.0.5 on 2026-07-24 10:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

TABLES = (
    "communication_email_template",
    "communication_email_template_version",
    "communication_lead_template_assignment",
    "communication_email_draft",
)


def seed_installation_partner_template(apps, schema_editor):
    Org = apps.get_model("common", "Org")
    EmailTemplate = apps.get_model("communications", "EmailTemplate")
    EmailTemplateVersion = apps.get_model("communications", "EmailTemplateVersion")
    subject = "Kennismaken als installatiepartner in regio Apeldoorn"
    body_text = """Beste {{ lead.first_name }},

Wij zijn Bruens Duurzame Technieken uit Apeldoorn. Wij bezoeken de klant, maken de offerte, bestellen de materialen en bereiden het werk voor. Voor de uitvoering zoeken we betrouwbare installatiepartners.

Zou je openstaan voor een korte kennismaking om te bespreken welk type installatiewerk en welke regio bij je passen?

Met vriendelijke groet,
{{ organization.name }}"""
    for org in Org.objects.all():
        template, created = EmailTemplate.objects.get_or_create(
            org=org,
            name="Installatiepartner – eerste contact",
            scope="org",
            owner=None,
            defaults={
                "description": "Eerste kennismaking met een mogelijke installatiepartner.",
                "purpose": "installer_outreach",
                "language": "nl",
                "subject": subject,
                "body_text": body_text,
            },
        )
        if created:
            EmailTemplateVersion.objects.create(
                org=org,
                template=template,
                version=1,
                subject=subject,
                body_text=body_text,
            )


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        for table in reversed(TABLES):
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("common", "0027_personalaccesstoken"),
        ("communications", "0001_initial"),
        ("leads", "0013_lead_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("purpose", models.CharField(blank=True, default="", max_length=100)),
                ("language", models.CharField(default="nl", max_length=10)),
                (
                    "scope",
                    models.CharField(
                        choices=[("org", "Organization"), ("personal", "Personal")],
                        default="org",
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(max_length=512)),
                ("body_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="common.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_template",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EmailTemplateVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("subject", models.CharField(max_length=512)),
                ("body_text", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="communications.emailtemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_template_version",
                "ordering": ("-version",),
            },
        ),
        migrations.CreateModel(
            name="EmailDraft",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=512)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True, default="")),
                ("follow_up_days", models.PositiveSmallIntegerField(default=5)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("template", "Template"),
                            ("ai", "AI"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_drafts",
                        to="leads.lead",
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="communications.mailboxconnection",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "sent_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_draft",
                        to="communications.leademailmessage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="communications.emailtemplateversion",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_draft",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LeadEmailTemplateAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_template_assignments",
                        to="leads.lead",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_assignments",
                        to="communications.emailtemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_lead_template_assignment",
                "ordering": ("-is_default", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["org", "is_active"], name="communicati_org_id_dd29e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["org", "scope", "owner"], name="communicati_org_id_f070e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "scope", "owner"),
                name="uniq_email_template_name_scope_owner",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplateversion",
            index=models.Index(
                fields=["org", "template", "-version"],
                name="communicati_org_id_fec018_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="uniq_email_template_version"
            ),
        ),
        migrations.AddIndex(
            model_name="emaildraft",
            index=models.Index(
                fields=["org", "lead", "-created_at"],
                name="communicati_org_id_60577e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildraft",
            index=models.Index(
                fields=["org", "status"], name="communicati_org_id_d79f55_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("org", "idempotency_key"),
                name="uniq_email_draft_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("follow_up_days__gte", 1), ("follow_up_days__lte", 30)
                ),
                name="email_draft_follow_up_days_range",
            ),
        ),
        migrations.AddIndex(
            model_name="leademailtemplateassignment",
            index=models.Index(
                fields=["org", "lead", "-is_default"],
                name="communicati_org_id_faace3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leademailtemplateassignment",
            constraint=models.UniqueConstraint(
                fields=("lead", "template"), name="uniq_email_template_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="leademailtemplateassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("lead",),
                name="uniq_default_email_template_per_lead",
            ),
        ),
        migrations.RunPython(
            seed_installation_partner_template,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
