# Generated by Django 6.0.5 on 2026-09-04 09:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

TABLE = "communication_email_signature"
BRUENS_ORG_ID = "ed15ae00-82e8-4b7b-bf42-a50db01650a6"
LEGACY_SIGNATURES = (
    """Met vriendelijke groet,

Jordan Bruens
Bruens Duurzame Technieken
055 203 21 91
info@bruensdt.nl
https://bruensdt.nl""",
    """Met vriendelijke groet,
{{ organization.name }}""",
)


def _without_legacy_signature(value):
    content = value.rstrip()
    for signature in LEGACY_SIGNATURES:
        if content.endswith(signature):
            return content[: -len(signature)].rstrip()
    return value


def seed_bruens_signature(apps, schema_editor):
    Org = apps.get_model("common", "Org")
    EmailDraft = apps.get_model("communications", "EmailDraft")
    EmailSignature = apps.get_model("communications", "EmailSignature")
    EmailTemplate = apps.get_model("communications", "EmailTemplate")
    EmailTemplateVersion = apps.get_model("communications", "EmailTemplateVersion")
    org = Org.objects.filter(pk=BRUENS_ORG_ID).first()
    if org is None:
        return
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT set_config('app.current_org', %s, false)",
                [BRUENS_ORG_ID],
            )
    EmailSignature.objects.update_or_create(
        org=org,
        defaults={
            "sender_name": "Jordan Bruens",
            "sender_role": "Eigenaar & installateur",
            "company_name": "Bruens Duurzame Technieken",
            "phone_number": "055 203 21 91",
            "email_address": "info@bruensdt.nl",
            "website_url": "https://bruensdt.nl",
            "address": "Laan van de Maagd 129, 7324 BT Apeldoorn",
            "logo_url": "https://bruensdt.nl/static/img/Logo_Bruens-DT.png",
            "primary_color": "#426451",
            "accent_color": "#F28C00",
            "certifications": [
                {
                    "name": "InstallQ erkend",
                    "url": "https://bruensdt.nl/installq-erkend-zonnepanelen-installateur-apeldoorn/",
                    "image_url": "https://bruensdt.nl/static/img/installq_bruensdt_erkenning.png",
                },
                {
                    "name": "Kiwa BRL100 / F-gassen",
                    "url": "https://bruensdt.nl/kiwa-brl100-f-gassen-gecertificeerd-airco-apeldoorn/",
                    "image_url": "https://bruensdt.nl/static/img/kiwa_bruensdt_gecertificeerd.png",
                },
                {
                    "name": "Zaptec Certified Installer",
                    "url": "https://bruensdt.nl/zaptec-certified-installer-apeldoorn/",
                    "image_url": "https://bruensdt.nl/static/img/zaptec-certified-bruens-duurzame-technieken.png",
                },
            ],
            "is_enabled": True,
        },
    )
    for draft in EmailDraft.objects.filter(org=org, status="draft"):
        cleaned = _without_legacy_signature(draft.body_text)
        if cleaned != draft.body_text:
            draft.body_text = cleaned
            draft.body_html = ""
            draft.save(update_fields=["body_text", "body_html", "updated_at"])
    for template in EmailTemplate.objects.filter(org=org):
        cleaned = _without_legacy_signature(template.body_text)
        if cleaned != template.body_text:
            template.body_text = cleaned
            template.current_version += 1
            template.save(update_fields=["body_text", "current_version", "updated_at"])
            EmailTemplateVersion.objects.create(
                org=org,
                template=template,
                version=template.current_version,
                subject=template.subject,
                body_text=cleaned,
            )


def unseed_bruens_signature(apps, schema_editor):
    EmailSignature = apps.get_model("communications", "EmailSignature")
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT set_config('app.current_org', %s, false)",
                [BRUENS_ORG_ID],
            )
    EmailSignature.objects.filter(org_id=BRUENS_ORG_ID).delete()


def enable_rls(apps, schema_editor):
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(get_enable_policy_sql(TABLE))


def disable_rls(apps, schema_editor):
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(get_disable_policy_sql(TABLE))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("common", "0027_personalaccesstoken"),
        ("communications", "0003_thread_read_state_and_reply_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSignature",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                (
                    "sender_role",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("website_url", models.URLField(blank=True, default="")),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(default="#426451", max_length=7)),
                ("accent_color", models.CharField(default="#F28C00", max_length=7)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "communication_email_signature",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org",), name="uniq_email_signature_per_org"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_bruens_signature, unseed_bruens_signature),
        migrations.RunPython(enable_rls, disable_rls),
    ]
