# Generated by Django 6.0.5 on 2026-09-04 10:00

from django.db import connection, migrations, models

BRUENS_ORG_ID = "ed15ae00-82e8-4b7b-bf42-a50db01650a6"


def set_bruens_review_links(apps, schema_editor):
    EmailSignature = apps.get_model("communications", "EmailSignature")
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT set_config('app.current_org', %s, false)",
                [BRUENS_ORG_ID],
            )
    EmailSignature.objects.filter(org_id=BRUENS_ORG_ID).update(
        review_score="9.6",
        review_count=283,
        reviews_url="https://www.bruensdt.nl/bekijk-al-onze-reviews/",
        projects_url="https://www.bruensdt.nl/projecten/",
    )


def clear_bruens_review_links(apps, schema_editor):
    EmailSignature = apps.get_model("communications", "EmailSignature")
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT set_config('app.current_org', %s, false)",
                [BRUENS_ORG_ID],
            )
    EmailSignature.objects.filter(org_id=BRUENS_ORG_ID).update(
        review_score=None,
        review_count=None,
        reviews_url="",
        projects_url="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_email_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsignature",
            name="projects_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="emailsignature",
            name="review_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailsignature",
            name="review_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="emailsignature",
            name="reviews_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.RunPython(set_bruens_review_links, clear_bruens_review_links),
    ]
